[package]
name = "rlgym_rs"
version = "0.1.0"
edition = "2021"
rust-version = "1.68.2"

[dependencies]
rocketsim_rs = { version = "0.33.0", features = ["glam"] }

[dev-dependencies]
fastrand = "2.1.0"

[profile.release]
lto = true
