[package]
name = "rlgym"
version = "0.2.0"
edition = "2024"
rust-version = "1.91"

[dependencies]
rlviser-rocketsim = {
  git = "https://github.com/VirxEC/rlviser-rocketsim.git",
}
rocketsim = {
  git = "https://github.com/VirxEC/RocketSim.git",
  branch = "vis-api"
}

[dev-dependencies]
rand = "0.10.1"

[profile.release]
debug = true
lto = true
